### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by dannymontalvo** [generalsystemsvehicle/frank-exchange-of-views#1]
Hello,

Thanks for your code, any example how to setup the client_id and client_secret ?.

Thanks.

**Comment by wells** [comment]
You'll need to setup an unpublished app on Zoom's app marketplace:
https://marketplace.zoom.us

You can either setup:
- A JWT app (requires developer privileges, which you may not have):
  https://marketplace.zoom.us/docs/guides/build/jwt-app
- An OAuth app:
  https://marketplace.zoom.us/docs/guides/build/oauth-app

For OAuth, please note that client credentials does not appear to function for many API endpoints (i.e. meetings, users, etc). You will want to store your access token and refresh token in a DB. Access tokens expire in 1 hour. Refresh tokens expire in 15 years. To make life easier, I recommend you refresh your access token every hour in a background job. 

To get the initial access_token and refresh_token, first Install your app to retrieve your authorization code via the callback URL, then:

```php
$oauth = new GeneralSystemsVehicle\Zoom\Api\OAuth;

$response = $oauth->authorizationCode([
    'authorization' => 'Basic '.base64_encode($clientId.':'.$clientSecret),
    'code' => $authorizationCode,
    'redirect_url' => 'callback',
]);
```

To refresh your access_token and refresh_token every hour:

```php
$oauth = new GeneralSystemsVehicle\Zoom\Api\OAuth;

$response = $oauth->refreshToken([
    'authorization' => 'Basic '.base64_encode($clientId.':'.$clientSecret),
    'refresh_token' => $refreshToken,
]);
```

Once you have a valid access_token from the API you can do something like:

```php
$meetings = new GeneralSystemsVehicle\Zoom\Api\Meetings;

$response = $meetings->index('me', [
    'authorization' => 'Bearer '.$accessToken,
    'query' => [
        'type' => 'live',
    ],
]);
```


Further support is something the folks at Zoom can give you.
